### ISSUE TITLE
Netlify CMS support notes

### ISSUE THREAD

**Issue by bharrisau** [narative/gatsby-theme-novela#294]
# Description
### Version of Novela you are using
0.13.1

### What are you trying to achieve?
Add Netlify CMS to project started with the theme starter. Below is how I've set it up - someone should be able to polish it and document it if they'd like. Basic setup is from https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/

1. Add CMS to your project `yarn add netlify-cms-app gatsby-plugin-netlify-cms`
2. Add the plugin to your `gatsby-config.yml`
3. Change all the `index.mdx` files to `index.md`. One liner `find content -name 'index.mdx' -exec sh -c 'git mv "$0" "${0%.mdx}.md"' '{}' \;`
4. Create the CMS config at `static/admin/config.yml`

```yaml
backend: # Set up your backend
  name: gitlab

local_backend: true # Optional if you want to use the local proxy mode

publish_mode: editorial_workflow
media_folder: media    # I'm not using these default media directories at the moment.
public_folder: /media

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    delete: true
    path: "{{slug}}/index"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "images"
    public_folder: "./images"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "select", options: ["Author 1"] }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Hero", name: "hero", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
```

Maybe you want to add the config for secret, subscription, canonical_url too. I'm not using them. The above is the basic setup - images and folder structure matches the existing content. I've not seen any issues with using the `.md` extension over the `.mdx`, but I'm not trying to do any JSX in my markdown either. The `gatsby-plugin-mdx` is set up with the `md` extension in the plugin config already.

Editing the `authors.yml` is blocked waiting on netlify/netlify-cms#531.

### References
#56 
#151 
#129
